require 'pry'

class Help
  
  attr_reader :user_input

  loop do
  
    puts "Enter 'help' to see a list of commands."
    puts "Enter the command name to bring up help for that command."
    puts "Enter 'exit' to exit and return to the main menu."

    @user_input = gets.chomp.to_s

    if @user_input == "help"
      puts " "
      puts "---"
      puts "Here is a list of commands: "
      puts "load"
      puts "queue count"
      puts "queue clear"
      puts "queue district"
      puts "queue print"
      puts "queue print by"
      puts "queue save to"
      puts "queue export html"
      puts "find"
      puts "---"
      puts " "
    elsif @user_input == "help load"
      puts " "
      puts "---"
      puts "This will erase any already loaded data."
      puts "If you don't specify a file, it will load the default..."
      puts "...which in this case is 'event_attendees.csv'."
      puts "You can specify a file by typing load <filepath>"
      puts "---"
      puts " "
    elsif @user_input == "help queue"
      puts " "
      puts "---"
      puts "Queue has many associated commands, please specify."
      puts "Type 'help' with no command to see a list of all commands."
      puts "---"
      puts " "
    elsif @user_input == "help queue count"
      puts " "
      puts "---"
      puts "This will output the number of records currently in queue."
      puts "---"
      puts " "
    elsif @user_input == "help queue clear"
      puts " "
      puts "---"
      puts "This will empty the queue."
      puts "---"
      puts " "
    elsif @user_input == "help queue district"
      puts " "
      puts "---"
      puts "If there are less than 10 entries, this will"
      puts "reach out to the Sunlight API to find district"
      puts "info for each entry."      
      puts "---"
      puts " "
    elsif @user_input == "help queue print"
      puts " "
      puts "---"
      puts "This will print out a tab-delimited table with"
      puts "the information from the queue."
      puts "---"
      puts " "
    elsif @user_input == "help queue print by"
      puts " "
      puts "---"
      puts "This will print data sorted by a particular attribute."
      puts "For example: 'queue print by zipcode' will sort data by zipcode."
      puts "---"
      puts " "
    elsif @user_input == "help queue save to"
      puts " "
      puts "---"
      puts "This will export the current queue to a CSV."
      puts "Enter a filename after 'to', otherwise it will use 'results.csv'"
      puts "---"
      puts " "
    elsif @user_input == "help queue export html"
      puts " "
      puts "---"
      puts "This will export the current queue to a valid HTML file."
      puts "Enter a filename after 'html', otherwise it will use 'results.html'."
      puts "---"
      puts " "
    elsif @user_input == "help find"
      puts " "
      puts "---"
      puts "This loads the queue with all records matching the criteria for the given attribute."
      puts "For example, 'find zipcode 20011' will print all records with a zipcode of 20011."
      puts "You can use the following attributes:"
      puts "last_name, first_name, email, zipcode, city, state, address, phone_number"      
      puts "---"
      puts " "
    elsif @user_input == "exit"
      puts " "
      puts "---"
      puts "Okay, goodbye."
      puts "---"
      puts " "
      exit
    else
      puts " "
      puts "---"
      puts "Incorrect input, try again."
      puts "---"
      puts " "
  end
    
  end
 end
